/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Lesson = IDL.Record({
  'startTime' : Time,
  'subject' : IDL.Text,
  'endTime' : Time,
  'dayOfWeek' : IDL.Text,
  'teacher' : IDL.Text,
  'classroom' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PaymentSettings = IDL.Record({
  'paymentProviderUrl' : IDL.Text,
  'paymentId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLesson' : IDL.Func([Lesson], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
  'getTimetable' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeLesson' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPaymentSettings' : IDL.Func([PaymentSettings], [], []),
  'setTimetable' : IDL.Func([IDL.Vec(Lesson)], [], []),
  'updateLesson' : IDL.Func([Lesson], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Lesson = IDL.Record({
    'startTime' : Time,
    'subject' : IDL.Text,
    'endTime' : Time,
    'dayOfWeek' : IDL.Text,
    'teacher' : IDL.Text,
    'classroom' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PaymentSettings = IDL.Record({
    'paymentProviderUrl' : IDL.Text,
    'paymentId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLesson' : IDL.Func([Lesson], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
    'getTimetable' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeLesson' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPaymentSettings' : IDL.Func([PaymentSettings], [], []),
    'setTimetable' : IDL.Func([IDL.Vec(Lesson)], [], []),
    'updateLesson' : IDL.Func([Lesson], [], []),
  });
};

export const init = ({ IDL }) => { return []; };